import { Router } from 'express';
import { leadController } from '../controllers/lead.controller';
import { validate } from '../middleware/validate';
import { assignLeadSchema, bulkImportSchema, createLeadSchema, mergeSchema, noteSchema, tagSchema, updateLeadSchema } from '../validators/lead.validators';
import { idParam, listQuery } from '../validators/common.validators';
import { authenticate, requireRoles } from '../auth/auth.middleware';
export const leadRouter=Router();
leadRouter.use(authenticate,requireRoles('Super Admin','Admin','Counselor','Sales Executive'));
leadRouter.post('/',validate({body:createLeadSchema}),leadController.create);
leadRouter.get('/',validate({query:listQuery}),leadController.list);
leadRouter.get('/export',leadController.bulkExport);
leadRouter.post('/bulk-import',validate({body:bulkImportSchema}),leadController.bulkImport);
leadRouter.post('/merge',validate({body:mergeSchema}),leadController.merge);
leadRouter.get('/:id',validate({params:idParam}),leadController.get);
leadRouter.put('/:id',validate({params:idParam,body:updateLeadSchema}),leadController.update);
leadRouter.delete('/:id',validate({params:idParam}),requireRoles('Super Admin','Admin'),leadController.remove);
leadRouter.post('/:id/assign',validate({params:idParam,body:assignLeadSchema}),leadController.assign);
leadRouter.post('/:id/notes',validate({params:idParam,body:noteSchema}),leadController.note);
leadRouter.post('/:id/tags',validate({params:idParam,body:tagSchema}),leadController.tags);
leadRouter.get('/:id/timeline',validate({params:idParam}),leadController.timeline);
