import { Router } from 'express';
import { authenticate, requireRoles } from '../auth/auth.middleware';
import { validate } from '../middleware/validate';
import { idParam } from '../validators/common.validators';
import { documentSchema, emailSchema, followUpSchema, notificationSchema, paymentSchema, taskSchema, whatsappSchema } from '../validators/module.validators';
import { courseController, cutoffController, documentController, emailController, followUpController, notificationController, parentController, paymentController, reportController, roundController, seatMatrixController, settingsController, studentController, taskController, templateController, upload, whatsappController } from '../controllers/module.controller';
function crudRoutes(controller:ReturnType<typeof import('../controllers/module.controller').crudController>,schema?: any){const r=Router();r.use(authenticate);r.post('/',schema?validate({body:schema}):[],controller.create);r.get('/',controller.list);r.get('/:id',validate({params:idParam}),controller.get);r.put('/:id',validate({params:idParam,body:schema?.partial?.()||schema}),controller.update);r.delete('/:id',validate({params:idParam}),controller.remove);return r;}
export const moduleRouter=Router();
moduleRouter.use('/students',crudRoutes(studentController));
moduleRouter.use('/parents',crudRoutes(parentController));
moduleRouter.use('/tasks',crudRoutes(taskController,taskSchema));
moduleRouter.use('/follow-ups',crudRoutes(followUpController,followUpSchema));
moduleRouter.use('/courses',crudRoutes(courseController));
moduleRouter.use('/cutoffs',crudRoutes(cutoffController));
moduleRouter.use('/counselling-rounds',crudRoutes(roundController));
moduleRouter.use('/seat-matrix',crudRoutes(seatMatrixController));
moduleRouter.use('/settings',crudRoutes(settingsController));
moduleRouter.use('/templates',crudRoutes(templateController));
moduleRouter.post('/documents/upload',authenticate,upload.single('file'),validate({body:documentSchema.pick({studentId:true,documentType:true})}),documentController.upload);
moduleRouter.get('/documents/signed-url',authenticate,documentController.signedUrl);
moduleRouter.post('/documents/:id/verify',authenticate,requireRoles('Super Admin','Admin','Counselor'),documentController.verify);
moduleRouter.post('/payments',authenticate,requireRoles('Super Admin','Admin','Accounts','Counselor'),validate({body:paymentSchema}),paymentController.create);
moduleRouter.post('/payments/:id/status',authenticate,validate({params:idParam}),paymentController.status);
moduleRouter.post('/payments/:id/refund',authenticate,requireRoles('Super Admin','Admin','Accounts'),validate({params:idParam}),paymentController.refund);
moduleRouter.post('/payments/:id/invoice',authenticate,validate({params:idParam}),paymentController.invoice);
moduleRouter.post('/email/send',authenticate,validate({body:emailSchema}),emailController.send);
moduleRouter.post('/whatsapp/send',authenticate,validate({body:whatsappSchema}),whatsappController.send);
moduleRouter.get('/whatsapp/webhook',whatsappController.webhookVerify);
moduleRouter.post('/whatsapp/webhook',whatsappController.webhook);
moduleRouter.post('/notifications/send',authenticate,validate({body:notificationSchema}),notificationController.send);
moduleRouter.post('/reports/:type',authenticate,requireRoles('Super Admin','Admin'),reportController.generate);
