import { Bell, Building2, CalendarCheck, FileText, IndianRupee, LayoutDashboard, Mail, Menu, Moon, Phone, Search, Shield, Sparkles, Sun, Users, X } from 'lucide-react';
import { useMemo, useState, type ReactNode } from 'react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { colleges, leads, payments, sessions, tasks } from './data';
import { leadScore, predictColleges } from './predictor';

const nav = ['Dashboard','Leads','Students','Colleges','Predictor','Counseling','Follow-ups','Documents','Payments','WhatsApp','Email','Reports','Admin'];
const icons = [LayoutDashboard, Users, Users, Building2, Sparkles, CalendarCheck, Bell, FileText, IndianRupee, Phone, Mail, BarChart, Shield];

export default function App(){
 const [active,setActive]=useState('Dashboard'); const [menu,setMenu]=useState(false); const [dark,setDark]=useState(false); const [query,setQuery]=useState('');
 const filtered=leads.filter(l=>`${l.studentName} ${l.mobile} ${l.state} ${l.leadStatus}`.toLowerCase().includes(query.toLowerCase()));
 const revenue=payments.filter(p=>p.status==='Paid').reduce((s,p)=>s+p.amount+p.gst,0); const pending=payments.filter(p=>p.status==='Pending').reduce((s,p)=>s+p.amount+p.gst,0);
 const stateData=Object.values(leads.reduce<Record<string,{state:string;leads:number}>>((a,l)=>{a[l.state]??={state:l.state,leads:0};a[l.state].leads++;return a;},{}));
 const courseData=Object.values(leads.reduce<Record<string,{course:string;count:number}>>((a,l)=>{a[l.interestedCourse]??={course:l.interestedCourse,count:0};a[l.interestedCourse].count++;return a;},{}));
 return <div className={dark?'dark':''}><div className="min-h-screen bg-slate-50 text-slate-900 dark:bg-slate-950 dark:text-slate-100">
  <aside className={`fixed inset-y-0 z-40 w-72 border-r border-blue-100 bg-white p-4 transition dark:border-slate-800 dark:bg-slate-900 lg:translate-x-0 ${menu?'translate-x-0':'-translate-x-full'}`}>
   <div className="mb-8 flex items-center justify-between"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-blue-600 text-xl font-black text-white">DA</div><div><h1 className="font-bold">Doctor Admission</h1><p className="text-xs text-slate-500">Medical CRM Suite</p></div></div><button className="lg:hidden" onClick={()=>setMenu(false)}><X/></button></div>
   <nav className="space-y-1">{nav.map((n,i)=>{const Icon=icons[i];return <button key={n} onClick={()=>{setActive(n);setMenu(false)}} className={`flex w-full items-center gap-3 rounded-2xl px-4 py-3 text-left text-sm font-medium ${active===n?'bg-blue-600 text-white shadow-lg shadow-blue-600/20':'text-slate-600 hover:bg-blue-50 dark:text-slate-300 dark:hover:bg-slate-800'}`}><Icon size={18}/>{n}</button>})}</nav>
  </aside>
  <main className="lg:pl-72"><header className="sticky top-0 z-30 border-b border-blue-100 glass dark:border-slate-800"><div className="flex items-center justify-between gap-3 px-4 py-3 md:px-8"><button className="lg:hidden" onClick={()=>setMenu(true)}><Menu/></button><div><p className="text-xs uppercase tracking-widest text-blue-600">{active}</p><h2 className="text-xl font-bold md:text-2xl">NEET UG & PG Admission Command Center</h2></div><div className="flex items-center gap-2"><button onClick={()=>setDark(!dark)} className="rounded-xl border p-2 dark:border-slate-700">{dark?<Sun/>:<Moon/>}</button><button className="rounded-xl bg-blue-600 px-4 py-2 text-sm font-semibold text-white">Add Lead</button></div></div></header>
   <section className="space-y-6 p-4 md:p-8">{active==='Dashboard'&&<Dashboard revenue={revenue} pending={pending} stateData={stateData} courseData={courseData}/>} {active==='Leads'&&<Leads filtered={filtered} query={query} setQuery={setQuery}/>} {active==='Predictor'&&<Predictor/>} {active==='Colleges'&&<Colleges/>} {active==='Payments'&&<Payments/>} {active==='Counseling'&&<Counseling/>} {active==='Follow-ups'&&<Followups/>} {!['Dashboard','Leads','Predictor','Colleges','Payments','Counseling','Follow-ups'].includes(active)&&<Module name={active}/>}</section>
  </main>
 </div></div>
}
function Card({title,value,sub}:{title:string;value:string|number;sub:string}){return <div className="rounded-3xl border border-blue-100 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><p className="text-sm text-slate-500">{title}</p><p className="mt-2 text-3xl font-black">{value}</p><p className="mt-1 text-xs text-blue-600">{sub}</p></div>}
function Dashboard({revenue,pending,stateData,courseData}:{revenue:number;pending:number;stateData:{state:string;leads:number}[];courseData:{course:string;count:number}[]}){const newToday=leads.filter(l=>l.createdAt.startsWith('2026-06-25')).length;return <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Card title="Total Leads" value={leads.length} sub="Across all channels"/><Card title="New Leads Today" value={newToday} sub="Auto captured"/><Card title="Qualified Leads" value={leads.filter(l=>!['New','Lost'].includes(l.leadStatus)).length} sub="Ready for counseling"/><Card title="Revenue Collected" value={`₹${revenue.toLocaleString('en-IN')}`} sub={`₹${pending.toLocaleString('en-IN')} pending`}/></div><div className="grid gap-4 xl:grid-cols-2"><Panel title="State-wise Lead Distribution"><ResponsiveContainer width="100%" height={280}><BarChart data={stateData}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="state"/><YAxis/><Tooltip/><Bar dataKey="leads" fill="#2563eb" radius={[8,8,0,0]}/></BarChart></ResponsiveContainer></Panel><Panel title="Course-wise Analytics"><ResponsiveContainer width="100%" height={280}><PieChart><Pie data={courseData} dataKey="count" nameKey="course" outerRadius={100}>{courseData.map((_,i)=><Cell key={i} fill={['#2563eb','#60a5fa','#93c5fd','#1d4ed8'][i%4]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></Panel></div><Panel title="AI Follow-up Suggestions"><div className="grid gap-3 md:grid-cols-3">{tasks.map(t=><div className="rounded-2xl bg-blue-50 p-4 dark:bg-slate-800" key={t.id}><b>{t.priority} priority</b><p className="text-sm">{t.title}</p></div>)}</div></Panel></>}
function Panel({title,children}:{title:string;children:ReactNode}){return <div className="rounded-3xl border border-blue-100 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h3 className="mb-4 text-lg font-bold">{title}</h3>{children}</div>}
function Leads({filtered,query,setQuery}:{filtered:typeof leads;query:string;setQuery:(v:string)=>void}){return <Panel title="Lead Management"><div className="mb-4 flex flex-col gap-3 md:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-3 text-slate-400" size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name, mobile, state, status" className="w-full rounded-2xl border p-3 pl-10 dark:border-slate-700 dark:bg-slate-950"/></div><select className="rounded-2xl border p-3 dark:border-slate-700 dark:bg-slate-950"><option>All Statuses</option></select></div><div className="overflow-x-auto"><table className="w-full min-w-[920px] text-sm"><thead><tr className="text-left text-slate-500"><th>Name</th><th>Mobile</th><th>State</th><th>Course</th><th>Score/AIR</th><th>Status</th><th>AI Score</th><th>Action</th></tr></thead><tbody>{filtered.map(l=><tr key={l.id} className="border-t dark:border-slate-800"><td className="py-3 font-semibold">{l.studentName}<p className="text-xs text-slate-500">{l.email}</p></td><td>{l.mobile}</td><td>{l.state}</td><td>{l.interestedCourse}</td><td>{l.neetScore} / {l.airRank}</td><td><span className="rounded-full bg-blue-100 px-3 py-1 text-blue-700 dark:bg-blue-950 dark:text-blue-200">{l.leadStatus}</span></td><td>{leadScore(l.neetScore,l.leadStatus,l.budget)}%</td><td><a className="font-semibold text-green-600" href={`https://wa.me/${l.whatsapp.replace(/\D/g,'')}`}>WhatsApp</a></td></tr>)}</tbody></table></div></Panel>}
function Predictor(){const [rank,setRank]=useState(65000); const result=useMemo(()=>predictColleges({score:560,rank,category:'OBC',state:'Karnataka',budget:2200000,course:'MBBS'}),[rank]);return <Panel title="AI College Predictor"><div className="grid gap-4 lg:grid-cols-3"><div className="space-y-3"><input type="range" min="1000" max="140000" value={rank} onChange={e=>setRank(+e.target.value)} className="w-full"/><p>AIR Rank: <b>{rank}</b></p><p className="text-sm text-slate-500">Combines rank fit, fee budget, state preference, category relaxation, and seat availability indicators.</p></div><div className="lg:col-span-2 grid gap-3">{result.map(c=><div key={c.id} className="rounded-2xl border p-4 dark:border-slate-800"><div className="flex justify-between"><b>{c.collegeName}</b><span className="text-blue-600">{c.probability}% probability</span></div><p className="text-sm">Fees ₹{c.managementQuotaFees.toLocaleString('en-IN')} • Seats {c.totalSeats} • {c.aiReason}</p></div>)}</div></div></Panel>}
function Colleges(){return <Panel title="College Database">{colleges.map(c=><div className="mb-3 rounded-2xl border p-4 dark:border-slate-800" key={c.id}><b>{c.collegeName}</b><p className="text-sm text-slate-500">{c.state} • {c.course} • Cutoff AIR {c.cutoffRank} • Management ₹{c.managementQuotaFees.toLocaleString('en-IN')}</p></div>)}</Panel>}
function Payments(){return <Panel title="Payment Management">{payments.map(p=><div className="mb-3 flex flex-col justify-between rounded-2xl border p-4 dark:border-slate-800 md:flex-row" key={p.id}><span><b>{p.studentName}</b><p>{p.package} • {p.paymentMode} • {p.transactionId}</p></span><b>₹{(p.amount+p.gst).toLocaleString('en-IN')} {p.status}</b></div>)}</Panel>}
function Counseling(){return <Panel title="Counseling Management">{sessions.map(s=><div className="rounded-2xl bg-blue-50 p-4 dark:bg-slate-800" key={s.id}><b>{s.studentName}</b><p>{s.counselor} • {new Date(s.scheduledAt).toLocaleString()} • <a className="text-blue-600" href={s.meetingLink}>Join meeting</a></p><p className="text-sm">{s.notes}</p></div>)}</Panel>}
function Followups(){return <Panel title="Daily Follow-up Dashboard">{tasks.map(t=><label className="mb-3 flex items-center gap-3 rounded-2xl border p-4 dark:border-slate-800" key={t.id}><input type="checkbox"/> <span><b>{t.title}</b><p className="text-sm text-slate-500">{t.owner} • {new Date(t.dueAt).toLocaleString()}</p></span></label>)}</Panel>}
function Module({name}:{name:string}){return <Panel title={`${name} Module`}><div className="grid gap-4 md:grid-cols-2"><div className="rounded-2xl bg-blue-50 p-5 dark:bg-slate-800"><h4 className="font-bold">Production workflows</h4><p className="text-sm text-slate-600 dark:text-slate-300">Role-aware screens for {name.toLowerCase()}, audit trails, notifications, templates, and Firestore-backed operations.</p></div><ResponsiveContainer width="100%" height={180}><AreaChart data={[{x:'Mon',y:12},{x:'Tue',y:19},{x:'Wed',y:16},{x:'Thu',y:24}]}><Area dataKey="y" fill="#bfdbfe" stroke="#2563eb"/><XAxis dataKey="x"/><Tooltip/></AreaChart></ResponsiveContainer></div></Panel>}
